const $ = selector => document.querySelector(selector);
const STORAGE = 'forgeline-chat-v1';
let docs = [], chats = [], activeId;
try { const saved=JSON.parse(localStorage.getItem(STORAGE)||'[]'); if(Array.isArray(saved))chats=saved.filter(c=>typeof c.id==='string'&&typeof c.title==='string'&&Array.isArray(c.messages)).slice(0,20); } catch { /* Storage may be disabled; chat still works in memory. */ }
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(chats.slice(0,20)));}catch{$('#chat-status').textContent='Browser storage is unavailable. This conversation will last until you leave the page.';}}
function node(tag,text,className){const el=document.createElement(tag);if(text)el.textContent=text;if(className)el.className=className;return el;}
function current(){return chats.find(c=>c.id===activeId);}
function newChat(){activeId=crypto.randomUUID();chats.unshift({id:activeId,title:'New conversation',messages:[]});chats=chats.slice(0,20);save();render();$('#chat-input').focus();}
function showSources(ids){const selected=ids?docs.filter(d=>ids.includes(d.id)):docs.filter(d=>d.approval_status==='approved');const target=$('#source-content');target.replaceChildren();for(const d of selected){const a=node('article');a.append(node('h3',d.title),node('small',`${d.doc_id} · v${d.revision} · ${d.section} · ${d.approval_status==='approved'?'Current':'Archived — not authoritative'}`),node('p',d.excerpt),node('small',`Owner: ${d.owner} · Effective: ${d.effective_date}`));target.append(a);}if(!selected.length)target.append(node('p','Documents are still loading. Please try again.'));$('#source-dialog').showModal();}
function render(){const chat=current();$('#welcome').hidden=!!chat?.messages.length;$('#messages').replaceChildren();for(const message of chat?.messages||[]){if(!['user','assistant'].includes(message.role)||typeof message.text!=='string')continue;const item=node('article',null,`chat-message ${message.role}`);item.append(node('h2',message.role==='user'?'You':'ForgeLine · document demo'));const body=node('div',null,'message-content');body.append(node('p',message.text));for(const id of message.sources||[]){const d=docs.find(d=>d.id===id);if(!d)continue;body.append(node('blockquote',d.excerpt));const btn=node('button',`${d.doc_id} · v${d.revision} · ${d.section}${d.approval_status==='superseded'?' · Archived':''}`,'source-button');btn.addEventListener('click',()=>showSources([id]));body.append(btn);}item.append(body);$('#messages').append(item);}$('#history').replaceChildren();for(const c of chats){const b=node('button',c.title);b.setAttribute('aria-current',String(c.id===activeId));b.addEventListener('click',()=>{activeId=c.id;render();});$('#history').append(b);}}
function answer(question){const q=question.toLowerCase();const equipment=$('#equipment').value;const base={role:'assistant',sources:[]};if(/emergency|fire\b|injur|bleeding|trapped|immediate danger/.test(q))return{...base,text:'Use posted site emergency procedures and designated responders. Do not wait for this demo. I cannot contact emergency services.',sources:['SAF-002:v2:Immediate danger']};if(/bypass|override|restart|release|ship(?:ment)?/.test(q))return{...base,text:'This demo cannot authorize bypasses, restart, product release or shipment. The fictional procedures reserve these decisions for the designated maintenance and quality leads.',sources:['SAF-001:v3:Restart authority','QLT-002:v2:Release']};if(/create|submit|send|email|issue|approve/.test(q))return{...base,text:'This chat can help you find fictional documentation, but cannot submit tasks, send email or write GitHub issues. Those integrations are not connected. Ask what information the relevant report requires.'};if(/compare|old and current|previous|120 minutes/.test(q))return{...base,text:'The fictional quality sampling interval changed from 120 minutes in archived v2 to 60 minutes in current v3. Both excerpts are below; only v3 is current.',sources:['QLT-001:v3:Sampling','QLT-001:v2:Sampling']};let ids=[];if(/e17/.test(q))ids=['MNT-001:v4:Fault report','SAF-001:v3:Jam escalation'];else if(/label|pk-04/.test(q))ids=['MNT-002:v2:Label mismatch report','QLT-002:v2:Trigger'];else if(/sampling|dimension|diameter|tolerance|px-20|sample/.test(q))ids=['QLT-001:v3:Sampling',...(/fail|outside|hold/.test(q)?['QLT-001:v3:Failure']:[])];else if(/near miss|nm-01/.test(q))ids=['SAF-002:v2:Near miss'];else if(/jam|guard/.test(q))ids=['SAF-001:v3:Access','SAF-001:v3:Jam escalation'];else if(/cv-12|schedule|250|maintenance interval/.test(q))ids=['MNT-001:v4:Schedule'];else if(/how often|inspect|maintenance/.test(q)){if(equipment==='CV-12')ids=['MNT-001:v4:Schedule'];else if(equipment==='PX-20')ids=['QLT-001:v3:Sampling'];else return{...base,text:'Which equipment or product do you mean: CV-12, PK-04 or PX-20? Include its ID in your next question or use the equipment selector.'};}if(!ids.length)return{...base,text:'I couldn’t match that question to the supported fictional examples. Try E17 on CV-12, PX-20 sampling, PK-04 labels, near-miss reporting or guard access. You can also browse Sources. This is a deterministic document-search demo, not a connected language model.'};return{...base,text:'Here are the relevant excerpts from the current fictional procedures. Open a source below to inspect its revision and owner.',sources:ids};}
$('#chat-form').addEventListener('submit',event=>{event.preventDefault();const question=$('#chat-input').value.trim();if(!question||!docs.length)return;if(!current())newChat();const chat=current();if(!chat.messages.length)chat.title=question.slice(0,65);chat.messages.push({role:'user',text:question,sources:[]},answer(question));$('#chat-input').value='';save();render();$('#chat-status').textContent='Answered from fictional documents. No external actions performed.';$('#chat-input').focus();$('#chat-bottom')?.scrollIntoView({block:'end'});$('.chat-bottom').scrollIntoView({block:'end',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
$('#chat-input').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();$('#chat-form').requestSubmit();}});
$('.suggestions').addEventListener('click',event=>{if(event.target.tagName==='BUTTON'){$('#chat-input').value=event.target.textContent;$('#chat-input').focus();}});
$('#new-chat').addEventListener('click',newChat);$('#show-docs').addEventListener('click',()=>showSources());$('#close-source').addEventListener('click',()=>$('#source-dialog').close());
activeId=chats[0]?.id;render();fetch('documents.json').then(r=>{if(!r.ok)throw Error('load failed');return r.json();}).then(data=>{docs=data;$('#send-chat').disabled=false;$('#chat-status').textContent='Ready · Six current fictional documents';render();}).catch(()=>{$('#chat-status').textContent='Could not load documents. Reload this page to retry.';});
